### ISSUE TITLE
Labelsin form

### ISSUE THREAD

**Issue by chin8** [scc-digitalhub/digitalhub-console#31]
Addding new labels to metadata of entities "sometimes"  make the form invalid
<img width="1920" alt="Screenshot 2024-05-15 at 09 50 41" src="https://github.com/scc-digitalhub/digitalhub-console/assets/4077653/446e772b-115c-42f1-96d5-5aa241266a2b">

**Comment by etomaselli** [comment]
Fixed with update in metadata schema
