### ISSUE TITLE
Add Spec title

### ISSUE THREAD

**Issue by chin8** [scc-digitalhub/digitalhub-console#38]
the spec label disappeared fgrom summmary of every entity

**Comment by etomaselli** [comment]
Field "title" is missing in spec schema and should be added in spec JSONschema in Core.

Workaround to add title in console code (should be done for every resource in its show/create/edit):

![image](https://github.com/scc-digitalhub/digitalhub-console/assets/33021319/e17829b6-0dcf-45c1-a653-9fde07509f54)

Using label instead, the title is duplicated:

![image](https://github.com/scc-digitalhub/digitalhub-console/assets/33021319/4fdb5449-3ced-41fc-b874-213ebe718a52)

![image](https://github.com/scc-digitalhub/digitalhub-console/assets/33021319/e71df39e-ee1d-4c91-b444-c7e7a8db847b)

**Comment by etomaselli** [comment]
Use workaround in every resource.
