### ISSUE TITLE
Error creating Artifact 

### ISSUE THREAD

**Issue by chin8** [scc-digitalhub/digitalhub-console#39]
Creating an Artifact, the field Path is not signed to required. If user tries to create it skipping that value, the core send an error to the console
![image](https://github.com/scc-digitalhub/digitalhub-console/assets/4077653/1b2ecd26-489c-4e48-91c2-eb144da31a48)

**Comment by etomaselli** [comment]
Check if anywhere in the console code the JSON schema is modified.

**Comment by chin8** [comment]
cache error. @matteo-s provided a fix with a deepcopy of the object
